default:
  content:
    - name: "Interactive Data Exploration with Streamlit"
      path: "./streamlit-income-share"
      description: "A Streamlit application makes it easy to transform your analysis into an interactive dashboard using Python."
      tag:
        - "Examples|Python|Streamlit"
      url: "/python-examples/streamlit/"
      image: "img/streamlit-income-share.png"

    - name: "Stock Pricing Dashboard with Dash"
      path: "./dash-stock-pricing"
      description: "A Dash application makes it easy to transform your analysis into an interactive dashboard using Python so users can ask and answer questions in real-time, without having to touch any code.h"
      tag:
        - "Examples|Python|Dash"
      url: "/python-examples/dash/"
      image: "img/dash-stock-pricing.png"

    - name: "Interactive Data Exploration with Shiny for Python"
      path: "./shiny-income-share"
      description: "Easy web apps for data science without the compromises."
      tag:
        - "Examples|Python|Shiny"
      url: "/python-examples/shiny/"
      image: "img/shiny-income-share.png"

    - name: "Voila Dashboards"
      path: "./jupyter-voila"
      description: "Turn your Jupyter Notebooks into dashboards with Voilà."
      tag:
        - "Examples|Python|Voila"
      url: "/python-examples/voila/"
      image: "img/voila.png"

    - name: "Serving Stock Information with FastAPI "
      path: "./fastapi-stock"
      description: "An API allows you to turn your models into production services that other tools and teams can use."
      tag:
        - "Examples|Python|FastAPI"
      url: "/python-examples/fastapi/"
      image: "img/fastapi-stock.png"

    - name: "Reticulated Image Classification with Shiny and PyTorch"
      path: "./reticulated-image-classifier"
      description: "A Shiny for R app powered by a PyTorch Model"
      tag:
        - "Examples|Python|Reticulate"
      url: "/python-examples/shiny-pytorch/"
      image: "img/reticulated-image-classifier.png"

    - name: "Literate Programming with Quarto"
      path: "./quarto-lightbox"
      description: "An open-source scientific and technical publishing system."
      tag:
        - "Examples|Python|Quarto"
      url: "/python-examples/quarto"
      image: "img/quarto-lightbox.png"